### ISSUE TITLE
Add generated quantities block for predictive checks and log_lik

### ISSUE THREAD

**Issue by erik-ringen** [ScottClaessens/coevolve#15]
It would be nice to have automated built-in prior/posterior checks in the generated quantities block, likewise for log_lik for model comparison purposes.

**Comment by erik-ringen** [comment]
I have now added automatic generation of predicted values (yrep) which works for either prior or posterior predictive checks. See example below:

`library(coevolve)
set.seed(5)

n <- 40
tree <- ape::rcoal(n)
VCV <- ape::vcv.phylo(tree, corr = T)
rho <- matrix(c(1, 0.5, 0.5, 1), byrow = 2, nrow = 2, ncol = 2)

x <- matrix(rnorm(n*2), nrow = n, ncol = 2)

y <- t(chol(VCV)) %*% x
y <- y %*% rho

d <- data.frame(
  id = tree$tip.label,
  x = y[,1],
  y = rbinom(n, size = 1, prob = plogis(y[,2])) 
)

fit_prior <- coev_fit(
  data = d,
  variables = list(
    x = "normal",
    y = "bernoulli_logit"
  ),
  id = "id",
  tree = tree,
  prior_only = T,
  # additional arguments for cmdstanr::sample()
  chains = 6,
  parallel_chains = 6,
  iter_warmup = 500,
  seed = 1
)

draws <- posterior::as_draws_rvars(fit_prior$fit$draws())
yrep1 <- posterior::draws_of(draws$yrep1)
yrep2 <- posterior::draws_of(draws$yrep2)

bayesplot::ppc_dens_overlay(y = d$x, yrep = yrep1[1:100, ])
bayesplot::ppc_bars(y = d$y, yrep = yrep2[1:100, ])`

**Comment by ScottClaessens** [comment]
Thanks for adding this in. I've updated the experimental branch as I had made a few changes to the master branch locally since you created that branch.

Currently the generated quantities block iteratively generates variables `yrep1`, `yrep2`, `yrep3`, etc. I recently moved back to a single matrix for `y`, so we should probably do the same for `yrep`. I can make this change.

Agree with the log likelihood addition 👍

**Comment by ScottClaessens** [comment]
In the commit 36705da, I modified the generated quantities block so that it produces a single `yrep` matrix variable.

The following code should work:

```
library(coevolve)
set.seed(5)

n <- 40
tree <- ape::rcoal(n)
VCV <- ape::vcv.phylo(tree, corr = T)
rho <- matrix(c(1, 0.5, 0.5, 1), byrow = 2, nrow = 2, ncol = 2)

x <- matrix(rnorm(n*2), nrow = n, ncol = 2)

y <- t(chol(VCV)) %*% x
y <- y %*% rho

d <- data.frame(
  id = tree$tip.label,
  x = y[,1],
  y = rbinom(n, size = 1, prob = plogis(y[,2])) 
)

fit_prior <- coev_fit(
  data = d,
  variables = list(
    x = "normal",
    y = "bernoulli_logit"
  ),
  id = "id",
  tree = tree,
  prior_only = T,
  chains = 6,
  parallel_chains = 6,
  iter_warmup = 500,
  seed = 1
)

draws <- posterior::as_draws_rvars(fit_prior$fit$draws())
yrep <- posterior::draws_of(draws$yrep)

bayesplot::ppc_dens_overlay(y = d$x, yrep = yrep[1:100,,1])
bayesplot::ppc_bars(y = d$y, yrep = yrep[1:100,,2])
```

**Comment by ScottClaessens** [comment]
I'm thinking it would be nice to write a small function `coev_predictive_check()` produce predictive plots using the above workflow. The function might take a fitted model object and a (vector of) variable name(s). That way the user doesn't have to know what `yrep` is under the hood.

**Comment by ScottClaessens** [comment]
The commit a73d320 is my first attempt at the log-likelihood calculation in the generated quantities block. However, I'm not sure this is the correct way to do it.

Currently, I've recorded the log-likelihood in a N x J matrix and then flattened the matrix into the vector `log_lik` to be fed into `loo()`. But would model comparisons using this vector make sense, given that multiple observations will come from the same species and given the whole issue of [doing leave-one-out cross-validation with phylogenetic data](https://discourse.mc-stan.org/t/phylogenetic-vignette-and-loo/4956)?

Anyway, the current approach should work with the following code:

```
library(coevolve)
set.seed(5)

# simulate data
n <- 40
tree <- ape::rcoal(n)
VCV <- ape::vcv.phylo(tree, corr = T)
rho <- matrix(c(1, 0.5, 0.5, 1), byrow = 2, nrow = 2, ncol = 2)

x <- matrix(rnorm(n*2), nrow = n, ncol = 2)

y <- t(chol(VCV)) %*% x
y <- y %*% rho

d <- data.frame(
  id = tree$tip.label,
  x = y[,1],
  y = rbinom(n, size = 1, prob = plogis(y[,2])) 
)

# fit model
fit <- 
  coev_fit(
    data = d,
    variables = list(
      x = "normal",
      y = "bernoulli_logit"
    ),
    id = "id",
    tree = tree,
    chains = 4,
    parallel_chains = 4,
    iter_warmup = 500,
    seed = 1
  )

# calculate loo
fit$fit$loo()
```

**Comment by ScottClaessens** [comment]
Closing this for now as I've merged the branch, but feel free to re-open if we want to revisit the log-likelihood question.

**Comment by ScottClaessens** [comment]
Closing this for now as I've merged the branch, but feel free to re-open if we want to revisit the log-likelihood question.
