### ISSUE TITLE
coev_fit() infers the wrong answer from simulated data before standardisation

### ISSUE THREAD

**Issue by ScottClaessens** [ScottClaessens/coevolve#26]
With the `coev_simulate_coevolution()` function, we can simulate the coevolution of multiple variables and test whether `coev_fit()` is able to recover the true data generating process.

In a previous iteration of the package, the simulation function standardised the continuous variables after the simulation was finished. In a simulation study with this function, I found that the model did pretty well at getting the right answer. However, in order to compare to the "true" $\Delta\theta_{z}$ value, I modified the simulation function to leave the variables unstandardised upon finishing the simulation.

Strangely, when using this new "unstandardised" simulation function, the model now tends to infer the wrong direction of coevolution. Here's a reproducible example for an example where we know that X → Y but not vice versa:

```r
library(coevolve)

# set seed
set.seed(1)

# simulate dataset where we know x -> y
sim <-
  coev_simulate_coevolution(
    n = 30,
    variables = c("x", "y"),
    selection_matrix = matrix(
      c(0.95, 0.00,
        0.90, 0.95),
      nrow = 2,
      ncol = 2,
      byrow = TRUE,
      dimnames = list(c("x", "y"), c("x", "y"))
      ),
    drift = c("x" = 0.05, "y" = 0.05),
    prob_split = 0.05
  )

# fit model without standardising variables
fit1 <-
  coev_fit(
    data = sim$data,
    variables = list(
      x = "normal",
      y = "normal"
    ),
    id = "species",
    tree = sim$tree,
    parallel_chains = 4,
    iter_sampling = 500,
    seed = 1
  )

# standardise variables
sim$data$x <- as.numeric(scale(sim$data$x))
sim$data$y <- as.numeric(scale(sim$data$y))

# fit model to standardised variables
fit2 <-
  coev_fit(
    data = sim$data,
    variables = list(
      x = "normal",
      y = "normal"
    ),
    id = "species",
    tree = sim$tree,
    parallel_chains = 4,
    iter_sampling = 500,
    seed = 1
  )
```

Here are the resulting $\Delta\theta_{z}$ values for both models. As you can see, only `fit2` gives the right answer.

```r
coev_plot_delta_theta(fit1)
```

![image](https://github.com/user-attachments/assets/162bf8b3-7d98-43ee-9320-0f98eff2102d)

```r
coev_plot_delta_theta(fit2)
```

![image](https://github.com/user-attachments/assets/fdaca67f-4677-4954-8a0e-2f54044b33e5)

@erik-ringen Maybe you can help here? Why do you think the model is doing this? I've tried this with a few different seeds and the same pattern emerges.

**Comment by ScottClaessens** [comment]
Thanks @erik-ringen. This makes sense. This raises a couple of questions regarding the package and our paper:

1. Should we standardise continuous variables by default under the hood? This is tricky because we would normally prefer to leave outcome variables on their natural measurement scale. And we can't do something similar for e.g. positive reals modelled as lognormal. But it's quite likely that people will apply the package to real-world continuous variables with quite different variances, and we wouldn't want them getting the wrong answer. An alternative here is to instead scale the priors under the hood, like we already do for the negative binomial case.
2. For the simulation in our paper, should we just standardise the variables as we had done before? This would mean that we won't be able to compare to the true value of $\Delta\theta_{z}$ that you had calculated.

**Comment by erik-ringen** [comment]
> Thanks @erik-ringen. This makes sense. This raises a couple of questions regarding the package and our paper:
> 
> 1. Should we standardise continuous variables by default under the hood? This is tricky because we would normally prefer to leave outcome variables on their natural measurement scale. And we can't do something similar for e.g. positive reals modelled as lognormal. But it's quite likely that people will apply the package to real-world continuous variables with quite different variances, and we wouldn't want them getting the wrong answer. An alternative here is to instead scale the priors under the hood, like we already do for the negative binomial case.

Other options would be to run a check whether all the variables the user has mapped onto a normal distribution have unit variance, and then give a warning message with explanation telling them to standardize and/or adjust the priors appropriately. In general I think it might be a good practice to output a warning message whenever the default priors are used, suggesting users that they might not be ideal and to do prior predictive checks.

Also, for positive reals I usually scale them by just dividing by the mean/median value.

> 2. For the simulation in our paper, should we just standardise the variables as we had done before? This would mean that we won't be able to compare to the true value of Δθz that you had calculated.

I think we can compare to the true value if we are careful. During the Δθz we would have to rescale a bit using the original means and sds.

**Comment by ScottClaessens** [comment]
We could maybe include an argument, such as `coev_fit(..., scale = TRUE)`, which standardises variables for users. Perhaps this could be set to TRUE as default. If the user sets `scale = FALSE`, then the function could return the warning you suggested if the variables do not have unit variance on the continuous / log scale.

I'm wondering if we could standardise as usual for "normal" and "student_t" variables and standardise on the log scale for "lognormal" variables?

```r
# simulate normal, student_t, and lognormal variables
n <- 1000
x <- rnorm(n, 0, 2)
y <- brms::rstudent_t(n, 3, 0, 2)
z <- rlnorm(n, 0, 2)
# standardisation approach under the hood if scale = TRUE
as.numeric(scale(x))
as.numeric(scale(y))
as.numeric(exp(scale(log(z)))
```

I'll go ahead with the standardised simulation for the paper, but keep a track of the means and SDs for the $\Delta\theta_{z}$ calculation.

**Comment by ScottClaessens** [comment]
I ran this simulation exercise again with a larger sample size (n = 200). The same pattern emerged even with the larger sample size: the model fitted to pre-standardised variables infers the wrong answer. So I'll work on implementing `scale = TRUE`.

```r
library(coevolve)
vars <- c("x", "y")
set.seed(1)
sim <-
  coev_simulate_coevolution(
    n = 200,
    variables = vars,
    selection_matrix = matrix(
      c(0.90, 0.00,
        0.85, 0.90),
      nrow = 2,
      byrow = TRUE,
      dimnames = list(vars, vars)
    ),
    drift = c("x" = 0.05, "y" = 0.05),
    prob_split = 0.05
  )
# fit model
fit1 <-
  coev_fit(
    data = sim$data,
    variables = list(
      x = "normal",
      y = "normal"
    ),
    id = "species",
    tree = sim$tree,
    parallel_chains = 4,
    seed = 1
  )
coev_plot_delta_theta(fit1)
```

![image](https://github.com/user-attachments/assets/9d1e2af2-ba26-4f52-b3e9-661d652f42aa)

```r
# standardise
sim$data$x <- as.numeric(scale(sim$data$x))
sim$data$y <- as.numeric(scale(sim$data$y))
# fit model
fit2 <-
  coev_fit(
    data = sim$data,
    variables = list(
      x = "normal",
      y = "normal"
    ),
    id = "species",
    tree = sim$tree,
    parallel_chains = 4,
    seed = 1
  )
coev_plot_delta_theta(fit2)
```

![image](https://github.com/user-attachments/assets/5e4b01c9-37bb-43f9-8822-36d72452fb05)

**Comment by ScottClaessens** [comment]
I have implement the `scale` argument for the `coev_fit()` function in f243ded. The argument determines whether continuous and positive real variables are standardised under the hood before model fitting. The argument is set to TRUE by default. If the user sets `scale = FALSE`, the function returns a warning that the user should be careful to set sensible priors rather than rely on default priors.
