### ISSUE TITLE
extract_samples for rethinking-style posterior lists

### ISSUE THREAD

**Issue by erik-ringen** [ScottClaessens/coevolve#28]
I have created a branch `extract-samples` to implement a function that takes a fit model from the package and returns a rethinking-style list of samples/draws. This function requires rethinking, which I don't think we want to make a hard dependency, but I think it is nice to have as I find this way of working with samples a lot more efficient and intuitive than the options given by the posterior package. The function is ready for review anytime.

**Comment by ScottClaessens** [comment]
Thanks Erik! I'll take a look at this soon.

**Comment by ScottClaessens** [comment]
Great, thanks Erik. I added some tests for this method and merged the branch in 8cc0b6a.
