### ISSUE TITLE
Allow non zero off-diagonals in the Q matrix

### ISSUE THREAD

**Issue by erik-ringen** [ScottClaessens/coevolve#31]
With typical panel data, you can simultaneously model both directed effects between variables (the A matrix) and covariance (Q matrix). However, I have found that in the phylogenetic case, trying to estimate both simultaneously leads to degenerate, multimodal posteriors. I think this is because the past states are not observed, there is not sufficient information. However in principle one should be able to estimate both with fossil data and/or informative priors on ancestral states.

A related issue is that, a user may wish to specify a mixture of covariances and directed effects in their model (e.g., A <--> B, B -> C, C -> A). It would be nice to give users this option, but I feel like we also need to give clear guidance on identification and interpretation of such models. I have had a simulation study in mind to see what can and cannot be recovered in the phylogenetic case.

**Comment by ScottClaessens** [comment]
Closing as I believe this is an old issue that has resurfaced.
