### ISSUE TITLE
What are the default priors?

### ISSUE THREAD

**Issue by adrianjaeggi** [ScottClaessens/coevolve#38]
Would be nice to highlight somewhere front and center (e.g. in the vignette) what default priors are used and why - currently the help page for coev_fit mentions that scaling affects the accuracy of priors, and some examples of manually-set priors appear in the vignette and the help page; in both cases A_offdiag = "normal (0,2) ".

I would just suggest something fairly simple like "these are the default priors:..." and "these priors are all weakly regularizing, which improves the model fitting and coservatism (e.g. Lemoine 2019 Oikos, McElreath 2020, etc.,)"

**Comment by adrianjaeggi** [comment]
Incidentally, if the default priors are fairly flat, then some error/warning messages could recommend setting more conservative priors (with examples). e.g. if chains don't converge (the Rhat > 1.05 warning) could include such a suggestion, in addition to re-parameterizing, increasing iterations, etc.

**Comment by ScottClaessens** [comment]
I have added the list of default priors and a brief justification for them in `help(coev_fit)`. I would prefer not to fill the vignette up with more technical information, as that documentation should be focused on usage.

Regarding the suggested error/warning messages, the `summary()` method for coevfit objects currently prints a warning like this for models that have not converged, similar to the warnings produced by the _brms_ package.
