### ISSUE TITLE
Full Q matrices by default

### ISSUE THREAD

**Issue by erik-ringen** [ScottClaessens/coevolve#45]
Currently, off-diagonals of the drift matrix (Q) are set to 0. I prescribed this based on some early results I had with some latent variable models where the cross-selection effects could not be identified simultaneously with the correlated drift. So I assumed independent drift terms. But this has always bothered me somewhat, and revisiting the issue I think what I had found previously was a corner-case.

I have done some experiments with the two vignette datasets (authority and primates) and both fit just fine with the full Q matrices being estimated (p.s. the cross-selection results from the Austronesian example are qualitatively the same, just a bit more uncertain I guess owing to the greater model complexity).

In any case, I think this should probably be the default to estimate going forward. It is only ~4 lines of code difference in the stan models, and should be easy to generalize. I think the only other change would be in the output of summary(object). @ScottClaessens I'll send you the example Stan files if you have time to implement, otherwise I can open a branch and do it.

**Comment by ScottClaessens** [comment]
Closing as this is an old issue.
