### ISSUE TITLE
Function to predict an evolutionary time series given some initial values

### ISSUE THREAD

**Issue by ScottClaessens** [ScottClaessens/coevolve#48]
Erik mentioned this in an email:

> Maybe the last feature I’d like to add before submission is to predict a time series given some initial values (which could for example be the model inferred ancestral states). I feel like this can really make the model’s behavior more transparent before introducing the equilibrium analyses. And it will generalize visualizing coevolution beyond the 2x2 case by using a common y-axis.

Here's an example of what this might look like:

![image](https://github.com/user-attachments/assets/2afc066c-6f20-4c82-b7e7-6fe76eab763d)

**Comment by ScottClaessens** [comment]
I mentioned this in my reply, but I think a good default for this plot would be to use the model-implied ancestral states as the starting values. Users could manually set their own starting values.

**Comment by ErikRingen** [comment]
I have drafted an initial version of this function on the associated branch.

**Comment by ErikRingen** [comment]
> Thanks! Are you happy to also work on the plotting function?

Yep, just pushed the function to the branch.
