### ISSUE TITLE
`coev_simulate_coevolution()` with non-zero means and ancestral states

### ISSUE THREAD

**Issue by ErikRingen** [ScottClaessens/coevolve#49]
To add flexibility/generality to the VAR(1) simulation of co-evolution with the function `coev_simulate_coevolution()`, we can add arguments for constants c to be added to the model for a non-zero mean, as well as arbitrary ancestral states. The defaults for these arguments can still be 0 for simplicity.

**Comment by ScottClaessens** [comment]
I added these arguments in 03898d3.
