### ISSUE TITLE
Gaussian/student-t responses handle drift incorrectly

### ISSUE THREAD

**Issue by ErikRingen** [ScottClaessens/coevolve#55]
OK, this issue is fairly complicated. To start, I noticed that at some point in the package history the `drift_sigma` values for Gaussian were set to `sqrt(diagonal(Q))`. When they were originally (or at least in the Gaussian Stan model template I initially sent) `sqrt(diagonal(VCV))` where `VCV` is the time dependent covariance matrix for a particular segment on the tree. I'm glad that I stumbled upon this because it made me realize the way I had suggested to handle Gaussian responses (and likewise student-t for the same reasons) is not valid. It would be valid if VCV was a diagonal matrix and the drift terms were independent, but they in general are not, even when `Q` is a diagonal matrix. The reason is that there is a dependency of `VCV` on `A_delta`, the time-dependent selection matrix. So you can end up with non-zero off-diagonals of VCV even when drift is independent as per `Q`. And now we are estimating full `Q` matrices by default, so this issue becomes even more important.

The most straightforward correct way to do it would be to model the Gaussian outcomes as multivariate normal, like this:

```
y[i]' ~ multi_normal( eta[t, tip_id[i]], VCV[t, tip_id[i]])
```

Where `eta[t, tip_id[i]]` is the expected value from the co-evolutionary process without the `drift_seg` component that we normally add.

This is fine if all responses are Gaussian, but we want something more general for mixtures of response types. So note that we can equivalently write the likelihood as:

```
vector[J] residuals = y[i]' - eta[t, tip_id[i]];
residuals ~ multi_normal( rep_vector(0.0, J), VCV[t, tip_id[i]])
```

This allows us to fill the residuals vector with a mixture of Gaussian residuals and latent-scale drift segments (which are a residual of sorts, as the difference between the latent value at the tips vs the previous time point). For example if we had Bernoulli responses:

```
parameters{
...
array[N_tree] matrix[N_obs, J] terminal_drift; // drift for the tips
}

model{
...
vector[J] residuals = terminal_drift[t, tip_id[i]]
residuals ~ multi_normal( rep_vector(0.0, J), VCV[t, tip_id[i]])
y[j] ~ bernoulli_logit( eta[t, tip_id[i]] + residuals )
}
```

Or with a mixture of Gaussian (1) and Bernoulli (2):

```
vector[J] residuals;
residuals[1] = y[i][1] - eta[t, tip_id[i]][1];
residuals[2] = terminal_drift[t, tip_id[i]];

residuals ~ multi_normal( rep_vector(0.0, J), VCV[t, tip_id[i]])
y[j] ~ bernoulli_logit( eta[t, tip_id[i]] + residuals )
```

In the case of missing Gaussian responses, you would also use the terminal drift parameters in place of the observed residuals. The only remaining issue to address is calculation of the pointwise log-likelihood, because the multivariate normal distribution is non-factorizable. I think we can use the approach outlined in this article:

Bürkner, P. C., Gabry, J., & Vehtari, A. (2021). Efficient leave-one-out cross-validation for Bayesian non-factorized normal and Student-t models. Computational Statistics, 36(2), 1243-1261.

The idea is to derive the conditional mean and conditional standard deviation for each component of the multivariate normal. Once again using the example of one Gaussian and one Bernoulli response:

```
generated quantities{
vector[N_obs, J] log_lik_temp; // log-likelihood

for (i in 1:N_obs) {
vector[J] mu_cond;
vector[J] sigma_cond;
vector[J] residuals;
matrix[J, J] cov_inv = inverse_spd(VCV[t, tip_id[i]]); 

residuals[1] = y[i][1] - eta[t, tip_id[i]][1];
residuals[2] = terminal_drift[t, tip_id[i]];

mu_cond = residuals - (cov_inv * residuals) ./ diagonal(cov_inv);
sigma_cond = sqrt(1/diagonal(cov_inv));

log_lik_temp[i,1] = normal_lpdf(mu_cond[1], sigma_cond[1]);
log_lik_temp[i,2] = bernoulli_logit_lpmf(eta[t, tip_id[i]] + residuals);
}
}

```

OK, I think that's it. I realize this implies a substantial change to the stancode generator function, so we should probably have some back-and-forths on this.

**Comment by ScottClaessens** [comment]
Thanks for spotting this @ErikRingen! I'm not sure where in the history that `sqrt(diagonal(Q))` was added - sorry about that!

I'm not fully up on the math here, but I will take your word for it that we need to change things.

Perhaps the best way to proceed is for you to email me some example Stan code for what needs to change. Maybe create an example model using `coev_make_stancode()` and then send me both (1) the original model code, and (2) the updated model code, so that I can see the diff and implement the changes in the function.

It would probably be best to adapt a model with both Gaussian and Bernoulli likelihoods.

**Comment by ErikRingen** [comment]
Just emailed you my proposed changes for the stan code, along with the code currently generated by `coev_make_stancode()`.

**Comment by ScottClaessens** [comment]
@ErikRingen quick question about the proposed Stan code. On line 124, you add the `terminal_drift` parameters:

```stan
array[N_tree] matrix[N_obs, J] terminal_drift; // drift for the tips
```

But there are no priors for these parameters in the model block. Is this an issue? Or is this because they are used to exactly define the `residuals` variable in the model block?

**Comment by ErikRingen** [comment]
> @ErikRingen quick question about the proposed Stan code. On line 124, you add the `terminal_drift` parameters:
> 
> ```stan
> array[N_tree] matrix[N_obs, J] terminal_drift; // drift for the tips
> ```
> 
> But there are no priors for these parameters in the model block. Is this an issue?
> 
> Or is this because these parameters are used to exactly define the `residuals` variable in the model block? So the "prior" for the `terminal_drift` parameters is technically on line 197:
> 
> ```stan
> lp[t] = multi_normal_cholesky_lpdf(residuals | rep_vector(0.0, J), cholesky_decompose(VCV_tips[t, tip_id[i]]));
> ```
> 
> I may be pinging more questions your way as I work through this code.

Exactly, the prior is assigned on line 197. However this is a good question because of what happens when some of the terminal drift parameters are not used, then no prior at all gets assigned to them. For example in the case of one bernoulli one gaussian, only one of the two terminal drift parameters is used. So to avoid sampling problems it would be better if we only include as my terminal drift parameters as there are non-Gaussian responses. Or, if it is easier to code-up, we can just add a std_normal() prior to the unused parameters.

**Comment by ScottClaessens** [comment]
But this line will apply to _all_ continuous variables, right?

```stan
lp[t] = multi_normal_cholesky_lpdf(residuals | rep_vector(0.0, J), cholesky_decompose(VCV_tips[t, tip_id[i]]));
```

So perhaps we should remove the Student T implementation?

**Comment by ErikRingen** [comment]
Yeah I had the same thought. I can try to figure out how to deal with the student-t observation as well, but for now maybe just remove.

**Comment by ScottClaessens** [comment]
Cool. I will remove both the student-t and lognormal distributions, to prepare for adding Gamma later.

**Comment by ScottClaessens** [comment]
Sorry, yes, that's what I meant by continuous.

**Comment by ScottClaessens** [comment]
Okay, I pushed a first draft of this change to the branch. I'm now just testing different models from the readme and vignette to see how well they fit.

**Comment by ScottClaessens** [comment]
So I ran the authority model from the readme with the new Stan code. We're getting some E-BFMI warnings, high Rhats, and low effective sample sizes. The `VCV_tips` parameters aren't shown in the model output, but they also tend to have higher Rhats and low effective sample sizes.

I will do some more digging, but in the meantime: @ErikRingen do you think we might be able to improve sampling by implementing a non-centered parameterisation of that `multi_normal` line in the model block? Or is it already non-centered?

```r
fit <-
  coev_fit(
    data = authority$data,
    variables = list(
      political_authority = "ordered_logistic",
      religious_authority = "ordered_logistic"
    ),
    id = "language",
    tree = authority$phylogeny,
    # manually set prior
    prior = list(A_offdiag = "normal(0, 2)"),
    # arguments for cmdstanr
    parallel_chains = 4,
    seed = 1
  )
```

```
All 4 chains finished successfully.
Mean chain execution time: 1837.0 seconds.
Total execution time: 2110.9 seconds.

Warning: 39 of 4000 (1.0%) transitions ended with a divergence.
See https://mc-stan.org/misc/warnings for details.

Warning: 3 of 4 chains had an E-BFMI less than 0.3.
See https://mc-stan.org/misc/warnings for details.
```

```r
summary(fit)
```

```
Variables: political_authority = ordered_logistic 
           religious_authority = ordered_logistic 
     Data: authority$data (Number of observations: 97)
Phylogeny: authority$phylogeny (Number of trees: 1)
    Draws: 4 chains, each with iter = 1000; warmup = 1000; thin = 1
           total post-warmup draws = 4000

Autoregressive selection effects:
                    Estimate Est.Error  2.5% 97.5% Rhat Bulk_ESS Tail_ESS
political_authority    -0.72      0.56 -2.07 -0.03 1.00     1454     2274
religious_authority    -0.76      0.57 -2.12 -0.04 1.00     1419     1953

Cross selection effects:
                                          Estimate Est.Error  2.5% 97.5% Rhat Bulk_ESS
political_authority ⟶ religious_authority     2.19      1.06  0.15  4.35 1.00      555
religious_authority ⟶ political_authority     1.80      1.08 -0.27  3.94 1.01      375
                                          Tail_ESS
political_authority ⟶ religious_authority     1035
religious_authority ⟶ political_authority     1428

Drift parameters:
                                             Estimate Est.Error  2.5% 97.5% Rhat
sd(political_authority)                          1.89      0.88  0.20  3.52 1.06
sd(religious_authority)                          1.53      0.77  0.19  3.09 1.03
cor(political_authority,religious_authority)     0.27      0.31 -0.41  0.77 1.01
                                             Bulk_ESS Tail_ESS
sd(political_authority)                            75      120
sd(religious_authority)                           128      150
cor(political_authority,religious_authority)      555     1114

Continuous time intercept parameters:
                    Estimate Est.Error  2.5% 97.5% Rhat Bulk_ESS Tail_ESS
political_authority     0.20      0.92 -1.66  1.98 1.00     5776     2665
religious_authority     0.24      0.94 -1.59  2.05 1.00     3611     1946

Ordinal cutpoint parameters:
                       Estimate Est.Error  2.5% 97.5% Rhat Bulk_ESS Tail_ESS
political_authority[1]    -1.31      0.89 -3.08  0.49 1.01     1257     2399
political_authority[2]    -0.56      0.87 -2.23  1.20 1.01     1925     2560
political_authority[3]     1.63      0.90 -0.06  3.42 1.00     3361     2768
religious_authority[1]    -1.56      0.92 -3.33  0.28 1.00     2939     3000
religious_authority[2]    -0.85      0.90 -2.60  0.93 1.00     3226     2946
religious_authority[3]     1.63      0.93 -0.08  3.52 1.00     2872     2993
```

```
Warning messages:
1: Parts of the model have not converged (some Rhats are > 1.05). Be careful when analysing the results! We recommend running more iterations and/or setting stronger priors. 
2: There were 39 divergent transitions after warmup. http://mc-stan.org/misc/warnings.html#divergent-transitions-after-warmup 
```

**Comment by ScottClaessens** [comment]
For an example of what I mean by the non-centered parameterisation of the `multi_normal()`, see the "Multivariate Reparameterizations" section here: https://mc-stan.org/docs/2_18/stan-users-guide/reparameterization-section.html

**Comment by ErikRingen** [comment]
> So I ran the authority model from the readme with the new Stan code. We're getting some E-BFMI warnings, high Rhats, and low effective sample sizes. The `VCV_tips` parameters aren't shown in the model output, but they also tend to have higher Rhats and low effective sample sizes.
> 
> I will do some more digging, but in the meantime: @ErikRingen do you think we might be able to improve sampling by implementing a non-centered parameterisation of that `multi_normal` line in the model block? Or is it already non-centered?
> 
> ```r
> fit <-
>   coev_fit(
>     data = authority$data,
>     variables = list(
>       political_authority = "ordered_logistic",
>       religious_authority = "ordered_logistic"
>     ),
>     id = "language",
>     tree = authority$phylogeny,
>     # manually set prior
>     prior = list(A_offdiag = "normal(0, 2)"),
>     # arguments for cmdstanr
>     parallel_chains = 4,
>     seed = 1
>   )
> ```
> 
> ```
> All 4 chains finished successfully.
> Mean chain execution time: 1837.0 seconds.
> Total execution time: 2110.9 seconds.
> 
> Warning: 39 of 4000 (1.0%) transitions ended with a divergence.
> See https://mc-stan.org/misc/warnings for details.
> 
> Warning: 3 of 4 chains had an E-BFMI less than 0.3.
> See https://mc-stan.org/misc/warnings for details.
> ```
> 
> ```r
> summary(fit)
> ```
> 
> ```
> Variables: political_authority = ordered_logistic 
>            religious_authority = ordered_logistic 
>      Data: authority$data (Number of observations: 97)
> Phylogeny: authority$phylogeny (Number of trees: 1)
>     Draws: 4 chains, each with iter = 1000; warmup = 1000; thin = 1
>            total post-warmup draws = 4000
> 
> Autoregressive selection effects:
>                     Estimate Est.Error  2.5% 97.5% Rhat Bulk_ESS Tail_ESS
> political_authority    -0.72      0.56 -2.07 -0.03 1.00     1454     2274
> religious_authority    -0.76      0.57 -2.12 -0.04 1.00     1419     1953
> 
> Cross selection effects:
>                                           Estimate Est.Error  2.5% 97.5% Rhat Bulk_ESS
> political_authority ⟶ religious_authority     2.19      1.06  0.15  4.35 1.00      555
> religious_authority ⟶ political_authority     1.80      1.08 -0.27  3.94 1.01      375
>                                           Tail_ESS
> political_authority ⟶ religious_authority     1035
> religious_authority ⟶ political_authority     1428
> 
> Drift parameters:
>                                              Estimate Est.Error  2.5% 97.5% Rhat
> sd(political_authority)                          1.89      0.88  0.20  3.52 1.06
> sd(religious_authority)                          1.53      0.77  0.19  3.09 1.03
> cor(political_authority,religious_authority)     0.27      0.31 -0.41  0.77 1.01
>                                              Bulk_ESS Tail_ESS
> sd(political_authority)                            75      120
> sd(religious_authority)                           128      150
> cor(political_authority,religious_authority)      555     1114
> 
> Continuous time intercept parameters:
>                     Estimate Est.Error  2.5% 97.5% Rhat Bulk_ESS Tail_ESS
> political_authority     0.20      0.92 -1.66  1.98 1.00     5776     2665
> religious_authority     0.24      0.94 -1.59  2.05 1.00     3611     1946
> 
> Ordinal cutpoint parameters:
>                        Estimate Est.Error  2.5% 97.5% Rhat Bulk_ESS Tail_ESS
> political_authority[1]    -1.31      0.89 -3.08  0.49 1.01     1257     2399
> political_authority[2]    -0.56      0.87 -2.23  1.20 1.01     1925     2560
> political_authority[3]     1.63      0.90 -0.06  3.42 1.00     3361     2768
> religious_authority[1]    -1.56      0.92 -3.33  0.28 1.00     2939     3000
> religious_authority[2]    -0.85      0.90 -2.60  0.93 1.00     3226     2946
> religious_authority[3]     1.63      0.93 -0.08  3.52 1.00     2872     2993
> ```
> 
> ```
> Warning messages:
> 1: Parts of the model have not converged (some Rhats are > 1.05). Be careful when analysing the results! We recommend running more iterations and/or setting stronger priors. 
> 2: There were 39 divergent transitions after warmup. http://mc-stan.org/misc/warnings.html#divergent-transitions-after-warmup 
> ```

Do you think this is systematically worse than before? I just ran this same code on the main branch and had 214 divergent transitions. Albeit the Rhats look better, but that might be just chance.

**Comment by ErikRingen** [comment]
> For an example of what I mean by the non-centered parameterisation of the `multi_normal()`, see the "Multivariate Reparameterizations" section here: https://mc-stan.org/docs/2_18/stan-users-guide/reparameterization-section.html

In the case of no Gaussian responses sure, we can do as it was before, i.e., sample from independent standard normals and multiply by the lower tri cholesky decomposition of the covariance matrix. But I don't think this is possible with Gaussian responses.

**Comment by ScottClaessens** [comment]
It was more the high Rhats that were concerning me rather than the divergences, especially for the sd and VCV_tip parameters. This often suggests that there's some kind of funnel that the sampler is finding difficult to explore. But if you don't think that it's possible to reparameterise, then maybe we just need to try running the sampler for longer or increasing adapt_delta.

**Comment by ErikRingen** [comment]
> It was more the high Rhats and low ESSs that were concerning me rather than the divergences, especially for the sd and VCV_tip parameters. This often suggests that there's some kind of funnel that the sampler is finding difficult to explore. But if you don't think that it's possible to reparameterise, then maybe we just need to try running the sampler for longer or increasing adapt_delta.

Indeed it does seem there is some moderate funnel behavior in the posterior geometry:

![image](https://github.com/user-attachments/assets/8b2fd494-7b89-466d-9536-5ce25729209f)

I'll think about this a bit. 

Also, maybe this is beyond the scope of this issue, but one could save some time by not computing the conditional means and std deviations when there are no gaussian variables, as this involves matrix inversion in the generated quantities block. In general we might consider an argument that allows users to only compute the pointwise log likelihood when they need it.

**Comment by ScottClaessens** [comment]
Interesting. Are you seeing any funneling with the `VCV_tip` parameters?

**Comment by ErikRingen** [comment]
> Interesting. Are you seeing any funneling with the `VCV_tip` parameters?

Not really, and actually what I posted before was not really a funnel as I understand it, which is usually a scatterplot of the draws of a parameter along with its hyperparameter (so like VCV_tips and terminal drift). If I am looking in the right place, these look OK:

![image](https://github.com/user-attachments/assets/872adff4-1092-4c86-bffb-8156424551c1)

**Comment by ScottClaessens** [comment]
Okay, good to know. I wonder why the correlation is happening among Q terms then.

Also, I added your suggestion about the pointwise log-likelihood as a separate issue (#61).

**Comment by ErikRingen** [comment]
I can confirm that running with a higher adapt_delta solves the issues, I tried with 2 different seeds on the authority dataset and had good convergence/ESS/mixing of chains. However I would still avoid using the multi_normal_cholesky() for datasets such as this with no gaussian traits, as I am sure the non-centered param is better.

**Comment by ScottClaessens** [comment]
Thanks for checking that!

Okay, so currently the code uses the centered version for all traits, regardless of their distribution. Would we want the package to detect whether Gaussian traits have been included and use the centered version, otherwise use the non-centered version? I'll try to think about how best to code that up.

**Comment by ScottClaessens** [comment]
If you have the energy, it would be useful if you could manually edit the Stan code that this branch currently produces for, say, a Bernoulli/Bernoulli case, so that I can see how the non-centering would work with the new architecture.

**Comment by ScottClaessens** [comment]
Thanks for sending the code along @ErikRingen. Sorry for the delay with this!

I've pushed another commit to this branch - `coev_make_stancode()` should now only include those terminal drift branches and the associated computation when there is at least one Gaussian trait. The code passes unit tests for that function, but I haven't tried fitting models with `coev_fit()` yet (or re-fitting the example models). I will test this soon. In the meantime, feel free to take the new code for a spin if you'd like.

**Comment by ErikRingen** [comment]
Thanks! I just checked it out and looks good/all tests are successful. I'll open a pull request.
