### ISSUE TITLE
Integration of tree uncertainty into coev_plot_predictive_check()

### ISSUE THREAD

**Issue by ErikRingen** [ScottClaessens/coevolve#57]
The current `coev_plot_predictive_check()` function requires the user to set a tree for which to predict. This is fine as an option, but probably as a default it would be nice to integrate over the tree-level uncertainty. This can be accomplished by pivoting the draws long with respect to tree_id, I believe.

**Comment by ScottClaessens** [comment]
I tried this without much luck, but it's likely I wasn't doing it properly!

**Comment by ErikRingen** [comment]
OK, I can give this a shot later, I have done similar things before with pp_check.

**Comment by ScottClaessens** [comment]
That would be useful, thank you!

**Comment by ScottClaessens** [comment]
Maybe then set `tree_id = NULL` as default, and then users can specify a particular tree if they would like.
