### ISSUE TITLE
`coev_plot_predictive_check()` requires ndraws and tree_id to be declared as integers

### ISSUE THREAD

**Issue by ErikRingen** [ScottClaessens/coevolve#59]
I noticed that `coev_plot_predictive_check()` requires both of these arguments to be specified as integers, i.e., `ndraws = 100L`. I think most users will not be familiar with having to include the L to declare as integer rather than double, and it seems like it would be better to check whether the input is a valid positive integer within the function, like this:

`
if (!is.null(ndraws)) {
    if (!as.integer(ndraws) == ndraws | ndraws <= 0 | length(ndraws) != 1) {
      stop2("Argument 'ndraws' must be a single positive integer.")
    }
`
Likewise for tree_id. Unless I am missing something about why it needs to be this way in this function but no other function.

**Comment by ScottClaessens** [comment]
Yep, this would be more user-friendly. I'll implement this.

**Comment by ScottClaessens** [comment]
Fixed in 63a57ae.
