### ISSUE TITLE
Allow `coev_pred_series()` to accept intervention values

### ISSUE THREAD

**Issue by ErikRingen** [ScottClaessens/coevolve#66]
Currently, this function can take varying starting values, but does not allow the user to hold any value constant. Using the same structure as `coev_calculate_theta`, I would like to allow the user to pass a named list of intervention values so that they can assess the impact of a (permanent) intervention over time. It would also be nice to eventually allow for non-permanent interventions (something like an 'impulse response function' that tracks the impact of an instantaneous, exogenous shock in one variable), but for now my focus is permanent interventions in line with the calculate of equilibrium trait values.

**Comment by ScottClaessens** [comment]
Cool idea!

**Comment by ErikRingen** [comment]
Implemented. I wasn't sure exactly how to pull this off when the stochastic drift is also included, so for now it is only possible with expected trait coevolution.
