### ISSUE TITLE
Gaussian measurement error

### ISSUE THREAD

**Issue by ErikRingen** [ScottClaessens/coevolve#71]
Currently, we can incorporate measurement error on the latent trait values by using random effects for repeated observations. However it would be nice to also have the option of traditional Gaussian measurement error on the outcomes, given that other phylogenetic packages usually permit this. It is not complex to code, just like this:

`y ~ normal(mu, sqrt(sigma^2 + SE^2))`

Where SE is the user-supplied standard error. @ScottClaessens if you like I can take a shot at implementing this? Or if you have the bandwidth you are of course welcome to.

**Comment by ScottClaessens** [comment]
This seems straightforward enough!

So each row in the dataset would have its own standard error? We would have to think about how best to add this to the arguments of `coev_fit()` in a way that makes sense. Should we add a `standard_error = NULL` argument, where users can specify a list / named vector that points to the correct column in the dataset?

**Comment by ErikRingen** [comment]
Something like that, it should definitely be a column in the dataset. But we also need a way to pair it to the appropriate trait. It should also only be used for Gaussian traits (and student-t if we add that likelihood).

**Comment by ScottClaessens** [comment]
So something like:

```r
coev_fit(
  data = d,
  variables = list(
    x = "normal",
    y = "bernoulli_logit"
  ),
  id = "id",
  tree = tree,
  measurement_error = list(x = "x_se"),
  ...
)
```

**Comment by ErikRingen** [comment]
Yep that looks good, I like that it matches the specification of variables.

**Comment by ScottClaessens** [comment]
Good. I don't mind which of us works on this. I'm on holiday for the next week, so maybe you could take it if it's something we want to get done quickly? Otherwise, happy to look at it when I get back.

**Comment by ErikRingen** [comment]
Sorry for not responding to this sooner, I pivoted fully to working on the manuscript with Adrian so that we can get that submitted ASAP. Happy to work on this together if you've already gotten started.

**Comment by ScottClaessens** [comment]
I haven't looked at this yet - prioritising fixing the various bugs and putting together the updated vignette for the workshop on Thursday. I can look properly after that.

**Comment by ErikRingen** [comment]
Yep, that's right. Visual check:

x <- rnorm(10, 0, 3.5)
se <- rexp(10, 2)

par(mfrow = c(1,2))
plot(x,  1:10)
for (i in 1:10) lines(x = c(x[i] - se[i], x[i], x[i] + se[i]), y = rep(i, 3))

sd_x <- sd(x)

x_scaled <- scale(x)

plot(x_scaled,  1:10)
for (i in 1:10) lines(x = c(x_scaled[i] - se[i]/sd_x, x_scaled[i], x_scaled[i] + se[i]/sd_x), y = rep(i, 3))

**Comment by ScottClaessens** [comment]
Thanks! Regarding missing data in the standard error columns, I'm currently not allowing missing standard errors where there are observed values for the focal variable. So, for example, this wouldn't be allowed:

```
           x      x_se
1 -0.1501532 0.7655439
2 -0.1376817 1.0158850
3  0.3229699 0.2220939
4 -0.4571351 1.0187139
5  1.0331418        NA
```

**Comment by ErikRingen** [comment]
Hmm, but what about cases where only some measures have known SEs? In that case maybe we just treated the SE as 0

**Comment by ScottClaessens** [comment]
I've currently required that SEs are positive reals. But I guess it's not an issue if SEs are zero, since this will just reduce to `y ~ normal(mu, sigma)`. So I'll change this requirement.

**Comment by ScottClaessens** [comment]
Okay, measurement error makes sense in the simple case of `y ~ normal(mu, sqrt(sigma^2 + SE^2))`. But we currently have a more complicated implementation of Gaussian variables in the model. @ErikRingen how should I go about adding measurement error to this part of the model block? (Below is an extract from the model block for a Bernoulli-Gaussian model)

```stan
if (!prior_only) {
    for (i in 1:N_obs) {
      vector[N_tree] lp = rep_vector(0.0, N_tree);
      for (t in 1:N_tree) {
        vector[J] residuals;
        residuals[1] = terminal_drift[t][i,1];
        if (miss[i,2] == 0) {
          residuals[2] = y[i,2] - eta[t,tip_id[i]][2];
          terminal_drift[t][i,2] ~ std_normal();
        } else {
          residuals[2] = terminal_drift[t][i,2];
        }
        lp[t] = multi_normal_cholesky_lpdf(residuals | rep_vector(0.0, J), cholesky_decompose(VCV_tips[t, tip_id[i]]));
        if (miss[i,1] == 0) lp[t] += bernoulli_logit_lpmf(to_int(y[i,1]) | eta[t,tip_id[i]][1] + residuals[1]);
      }
      target += log_sum_exp(lp);
    }
  }
```

**Comment by ErikRingen** [comment]
I am pretty sure you can just add the squared standard errors to the diagonals of the traits with measurement error.

**Comment by ScottClaessens** [comment]
So, something like this? Where `se` is declared as a [N_obs, N_variable] data matrix with squared standard errors, set to zero for non-normal variables and for observations with no measurement error.

```stan
if (!prior_only) {
    for (i in 1:N_obs) {
      vector[N_tree] lp = rep_vector(0.0, N_tree);
      for (t in 1:N_tree) {
        vector[J] residuals;
        residuals[1] = terminal_drift[t][i,1];
        if (miss[i,2] == 0) {
          residuals[2] = y[i,2] - eta[t,tip_id[i]][2];
          terminal_drift[t][i,2] ~ std_normal();
        } else {
          residuals[2] = terminal_drift[t][i,2];
        }
        lp[t] = multi_normal_cholesky_lpdf(residuals | rep_vector(0.0, J), cholesky_decompose(add_diag(VCV_tips[t, tip_id[i]], se[i,])));
        if (miss[i,1] == 0) lp[t] += bernoulli_logit_lpmf(to_int(y[i,1]) | eta[t,tip_id[i]][1] + residuals[1]);
      }
      target += log_sum_exp(lp);
    }
  }
```

**Comment by ErikRingen** [comment]
Yes that's right. I am pretty sure it is that simple because the variance of the Gaussian errors are just additive.

**Comment by ScottClaessens** [comment]
Great, thanks! I've pushed some changes to this branch implementing the `measurement_error` argument in `coev_fit()`. Here's a peek at it in action. The model seems to fit fine.

I've still yet to write tests etc., but feel free to have a play around with this in the meantime @ErikRingen.

```r
library(coevolve)

set.seed(1)

tree <- ape::rcoal(5)

d <- data.frame(
  id = tree$tip.label,
  x = rbinom(5, 1, 0.5),
  y = rnorm(5),
  y_se = rexp(5)
)

m <- coev_fit(
  data = d,
  variables = list(
    x = "bernoulli_logit",
    y = "normal"
  ),
  id = "id",
  tree = tree,
  measurement_error = list(y = "y_se"),
  adapt_delta = 0.99,
  parallel_chains = 4
)

summary(m)
```

```
Variables: x = bernoulli_logit 
           y = normal 
     Data: d (Number of observations: 5)
Phylogeny: tree (Number of trees: 1)
    Draws: 4 chains, each with iter = 1000; warmup = 1000; thin = 1
           total post-warmup draws = 4000

Autoregressive selection effects:
  Estimate Est.Error  2.5% 97.5% Rhat Bulk_ESS Tail_ESS
x    -0.89      0.62 -2.33 -0.05 1.00     2966     1667
y    -0.95      0.63 -2.41 -0.04 1.00     2262     1305

Cross selection effects:
      Estimate Est.Error  2.5% 97.5% Rhat Bulk_ESS Tail_ESS
x ⟶ y     0.04      0.94 -1.78  1.84 1.00     3948     3084
y ⟶ x     0.06      0.96 -1.81  1.94 1.00     3287     2724

Drift parameters:
         Estimate Est.Error  2.5% 97.5% Rhat Bulk_ESS Tail_ESS
sd(x)        0.80      0.59  0.03  2.19 1.01      362      760
sd(y)        0.73      0.52  0.04  1.96 1.00     2403     1761
cor(x,y)     0.01      0.33 -0.62  0.62 1.00     4863     2622

Continuous time intercept parameters:
  Estimate Est.Error  2.5% 97.5% Rhat Bulk_ESS Tail_ESS
x    -0.16      0.87 -1.83  1.56 1.00     4622     3054
y    -0.21      0.79 -1.75  1.31 1.00     4052     3161

Warning message:
There were 4 divergent transitions after warmup. http://mc-stan.org/misc/warnings.html#divergent-transitions-after-warmup
```
