### ISSUE TITLE
Function to save coevolve fits as rds

### ISSUE THREAD

**Issue by ErikRingen** [ScottClaessens/coevolve#76]
I wouldn't consider this a priority, but it would be nice to have a function sort of like the fixtures helpers so that users could save their coev fits for future use.

**Comment by ScottClaessens** [comment]
I agree that this would be useful. Annoyingly, cmdstan objects point to a csv file with samples on the local computer. In my experience, this has made it difficult to save and reload model fits with .rds files. But it's possible I've been doing it wrong.

This function may be useful: https://mc-stan.org/cmdstanr/reference/fit-method-save_object.html

**Comment by ScottClaessens** [comment]
I added the function `save_coevfit()` in 3128147. The function can be used to correctly save coevfit objects as rds files.
