### ISSUE TITLE
`coev_plot_flowfield()` for more than 2 traits

### ISSUE THREAD

**Issue by ErikRingen** [ScottClaessens/coevolve#82]
I was taking a look at the code for `coev_plot_flowfield()` and it seems like it would not be correct for more than 2 traits, because it does not track indirect effects (e.g., y1 -> y2 -> y3). Even if only two traits can be plotted at a time, all need to be tracked in the system.

**Comment by ScottClaessens** [comment]
Currently, the function can only take two variables, set with the `var1` and `var2` arguments. If there are more than two variables in the model, the OU function holds all other variables at their median values during the computation (see [here](https://github.com/ScottClaessens/coevolve/blob/c40003c33447624ba6d0d077de8cf8e9d0ce4655/R/coev_plot_flowfield.R#L127-L158)). Do you think this is the right approach?

**Comment by ErikRingen** [comment]
I don't think we should do this now that I have been fitting models with more than 2 traits, because it can really obscure the dynamics and give a misleading picture. I am working on a 3D flowfield for the paper, so maybe we can use that as a template for a refactor of this function.

**Comment by ScottClaessens** [comment]
Okay, makes sense. I'll wait to see what you come up with. Note that any changes will also apply to `coev_plot_selection_gradient()` which currently takes the same approach (it holds all other values constant).

**Comment by ErikRingen** [comment]
OK I tried a few different ways but nothing was very satisfying/nice to look at. You can do multiple 2D flow fields for each pair of traits, but then you still have the problem of 3rd+ variables have to be held constant at a given point in the state space for the velocities to be defined. And this can produce really misleading portraits in my opinion. Perhaps we leave as is in the package but print a warning to users if they have more than 2 traits?

**Comment by ScottClaessens** [comment]
A warning sounds good. I'll implement this.
